name: Type Check
on: [push, pull_request]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/.local/share/uv
        key: uv-${{ runner.os }}-3.12.8

    - name: Set up venv
      run: |
        uv python install 3.12.8
        uv venv --python 3.12.8
        source .venv/bin/activate
        uv pip install poethepoet ruff pyright

    - name: Poe typecheck
      run: source .venv/bin/activate && poe typecheck
